services:
  fluentd:
    image: grafana/fluent-plugin-loki:master
    container_name: fluentd
    ports:
      - "24224:24224"
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: ${LOKI_URL:?}
      LOKI_USERNAME:
      LOKI_PASSWORD:
    volumes:
      - ${PWD}/fluent.conf:/fluentd/etc/fluent.conf:ro
      - ${PWD}/loki.conf:/fluentd/etc/loki.conf:ro
